const GET_LIST_DATA = "GET_LIST_DATA"
const SET_LOGIN_USER = "SET_LOGIN_USER"
const SET_REG_USER = "SET_REG_USER"
const SET_ADD_DATA = "SET_ADD_DATA"
export {
  GET_LIST_DATA,
  SET_REG_USER,
  SET_LOGIN_USER,
  SET_ADD_DATA
}